<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChoPilot.Core\ChoPilot.Core.csproj" />
    <ProjectReference Include="..\ChoPilot.Mapping\ChoPilot.Mapping.csproj" />
  </ItemGroup>

</Project>
